
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kzldlgr
  password: postgres

development:
  <<: *default
  database: rails_app_blog_development

  
test:
  <<: *default
  database: rails_app_blog_test

production:
  <<: *default
  database: rails_app_blog_production
  username: rails_app_blog
  password: <%= ENV["RAILS_APP_BLOG_DATABASE_PASSWORD"] %>
